kind: IngressController
apiVersion: operator.openshift.io/v1
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  defaultCertificate:
    name: ingress-cert-secret
  endpointPublishingStrategy:
    loadBalancer:
{{ if semverCompare "~4.12.0" .Values.openshift_version }}
      allowedSourceRanges:
      - "0.0.0.0/0"
{{ end }}
  domain: apps.{{ .Values.cluster_name }}.{{ .Values.base_domain }}
