# Default values for hardedning.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cluster_name:
whitelist_internal_registry: true
enable_image_whitelist: false

cluster_banner:
  backgroundColor: '#0071BC' # blue
  textColor: '#FFFFFF' # white