{{ range $appProject := .Values.appProjects }}
{{ range $application := $appProject.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application.name }}
  namespace: openshift-gitops
spec:
  project: {{ $appProject.name }}
  destination:
    name: in-cluster
    namespace: {{ $appProject.name }}
  source:
    directory:
      recurse: false
    helm:
      valueFiles:
        - {{ $application.valuesFile | default $appProject.defaultValuesFile | squote }}
    repoURL: {{ squote $appProject.gitUrl }}
    path: {{ squote $application.gitPath }}
    targetRevision: {{ $appProject.gitBranch | default "main" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
{{ end }}
{{ end }}
