{{- range $role := $.Values.roles }}
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $role }}
roleRef:
  name: {{ $role }}
subjects:
- kind: ServiceAccount
  name: splunk
  namespace: openshift-logging
{{- end }}
