---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: splunk-log-forwarder 
  namespace: openshift-logging 
spec:
  serviceAccountName: splunk
  outputs:
  {{- range $splunk := $.Values.splunks }}
    - name: {{ $splunk.name }}
      secret:
        name: {{ $splunk.secret }}
      type: splunk 
      url: {{ $splunk.fqdn }}
  {{- end }}
  pipelines:
  {{- range $splunk := $.Values.splunks }}
    - inputRefs:
      {{- range $inputRef := $splunk.inputRefs }}
      - {{ print $inputRef }}
      {{- end }}
      name: {{ $splunk.name }}
      outputRefs:
        - {{ $splunk.name }}
  {{- end }}
